"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
const ADMIN="gabrialzueta@gmail.com";
type Match={round:number,team:string,opponent:string,home_score:number,away_score:number,yellow_cards:number,red_cards:number,status:"scheduled"|"live"|"finished"};
export default function AdminPage(){const[allowed,setAllowed]=useState<boolean|null>(null);const[matches,setMatches]=useState<Match[]>([]);const[busy,setBusy]=useState("");
const load=async()=>{const {data}=await supabase.from("quini_live_matches").select("*").eq("round",1).order("team");setMatches((data||[]) as Match[])};
useEffect(()=>{let active=true;const verify=async()=>{const {data:{session}}=await supabase.auth.getSession();let user=session?.user||null;if(session){const fresh=await supabase.auth.getUser();user=fresh.data.user||user}const ok=user?.email?.trim().toLowerCase()===ADMIN;if(!active)return;setAllowed(ok);if(ok)await load()};void verify();const {data:listener}=supabase.auth.onAuthStateChange(()=>void verify());return()=>{active=false;listener.subscription.unsubscribe()}},[]);
const act=async(team:string,action:string)=>{setBusy(team+action);const {data:{session}}=await supabase.auth.getSession();const res=await fetch("/api/admin/live",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session?.access_token},body:JSON.stringify({round:1,team,action})});if(res.ok)await load();setBusy("")};
if(allowed===null)return <main className="adminGate"/>;if(!allowed)return <main className="adminGate"><section><h1>Acceso restringido</h1><p>Este panel no está disponible para esta cuenta.</p><button onClick={()=>location.href="/"}>Volver a QuiniDerio</button></section></main>;
return <main className="adminPage"><header><button onClick={()=>location.href="/"}>‹ Volver</button><div><small>QUINIDERIO</small><h1>Panel Admin</h1></div></header><section className="adminHero"><span>JORNADA 1</span><h2>Control en directo</h2><p>Los cambios se guardan en Supabase y se comparten con todos los usuarios.</p></section><div className="adminGrid">{matches.map(m=><article key={m.team}><div><small>{m.status==="live"?"EN JUEGO":m.status==="finished"?"FINALIZADO":"PARTIDO"}</small><h3>{m.team} · {m.opponent}</h3></div><div className="adminScore"><div><button aria-label="Quitar gol local" disabled={!!busy||m.status==="finished"||m.home_score<=0} onClick={()=>act(m.team,"homeGoalRemove")}>−</button><button aria-label="Añadir gol local" disabled={!!busy||m.status==="finished"} onClick={()=>act(m.team,"homeGoal")}>+</button></div><strong>{m.home_score} - {m.away_score}</strong><div><button aria-label="Quitar gol visitante" disabled={!!busy||m.status==="finished"||m.away_score<=0} onClick={()=>act(m.team,"awayGoalRemove")}>−</button><button aria-label="Añadir gol visitante" disabled={!!busy||m.status==="finished"} onClick={()=>act(m.team,"awayGoal")}>+</button></div></div><div className="adminActions"><button disabled={!!busy||m.status!=="scheduled"} onClick={()=>act(m.team,"start")}>Iniciar partido</button><button disabled={!!busy||m.status!=="live"} onClick={()=>act(m.team,"yellow")}>Amarilla · {m.yellow_cards}</button><button disabled={!!busy||m.status!=="live"} onClick={()=>act(m.team,"red")}>Roja · {m.red_cards}</button><button disabled={!!busy||m.status!=="live"} onClick={()=>{if(window.confirm("¿Finalizar este partido? Podrás reabrirlo desde el panel."))void act(m.team,"finish")}}>Finalizar</button>{m.status==="finished"&&<button disabled={!!busy} onClick={()=>{if(window.confirm("¿Reabrir este partido para corregirlo?"))void act(m.team,"reopen")}}>Reabrir</button>}</div></article>)}</div><section className="adminBulk"><h2>Control de jornada</h2><p>Acciones globales para corregir o cerrar la jornada.</p><button disabled={!!busy||!matches.some(m=>m.status==="live")} onClick={()=>{if(window.confirm("¿Finalizar todos los partidos que están en juego?"))matches.filter(m=>m.status==="live").forEach(m=>void act(m.team,"finish"))}}>Finalizar partidos en juego</button></section></main>}