"use client";
import {useEffect,useState} from "react";
function keyBytes(s:string){const p="=".repeat((4-s.length%4)%4);return Uint8Array.from(atob((s+p).replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0))}
function identity(){let id=localStorage.getItem("quiniderio-player-id");if(!id){id=crypto.randomUUID();localStorage.setItem("quiniderio-player-id",id)}let name="Jugador";try{name=JSON.parse(localStorage.getItem("quiniderio-player")||"{}").name||name}catch{}return{id,name}}
function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1)}
function isStandalone(){return window.matchMedia("(display-mode: standalone)").matches||(navigator as Navigator&{standalone?:boolean}).standalone===true}
export async function enablePush(){if(isIOS()&&!isStandalone())throw new Error("ios-install");if(!("serviceWorker"in navigator)||!("PushManager"in window)||!("Notification"in window))throw new Error("unsupported");if(Notification.permission==="denied")throw new Error("denied");if(await Notification.requestPermission()!=="granted")return false;await navigator.serviceWorker.register("/sw.js");const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){const k=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!k)throw new Error("vapid");sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(k)})}const j=sub.toJSON(),p=identity();const r=await fetch("/api/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerId:p.id,name:p.name,subscription:{endpoint:sub.endpoint,keys:j.keys}})});if(!r.ok)throw new Error("save");localStorage.setItem("quiniderio-notifications","true");window.dispatchEvent(new CustomEvent("quiniderio-push-state",{detail:true}));return true}
export async function disablePush(){const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(sub){await fetch("/api/push",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe()}localStorage.setItem("quiniderio-notifications","false");window.dispatchEvent(new CustomEvent("quiniderio-push-state",{detail:false}))}
export default function PushPrompt(){const[show,setShow]=useState(false),[busy,setBusy]=useState(false),[err,setErr]=useState("");useEffect(()=>{if(!("serviceWorker"in navigator)||!("Notification"in window))return;navigator.serviceWorker.register("/sw.js").catch(()=>{});if(!localStorage.getItem("quiniderio-push-prompt-seen-v1")&&localStorage.getItem("quiniderio-player"))setTimeout(()=>setShow(true),700)},[]);if(!show)return null;const close=()=>{localStorage.setItem("quiniderio-push-prompt-seen-v1",String(Date.now()));setShow(false)};return <div className="pushPromptBackdrop"><section className="pushPrompt" role="dialog" aria-modal="true"><div className="pushBell" aria-hidden="true"><svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg></div><h2>No te pierdas la jornada</h2><p>Activa las notificaciones para recibir recordatorios si aún no has enviado tu quiniela, además de avisos de cierre y resultados.</p>{err&&<small>{err}</small>}<button disabled={busy} onClick={async()=>{setBusy(true);try{if(await enablePush())close();else setErr("Necesitamos permiso para enviarte avisos.")}catch(e){const m=e instanceof Error?e.message:"";setErr(m==="ios-install"?"En iPhone, añade QuiniDerio a la pantalla de inicio y ábrela desde su icono para activar las notificaciones.":m==="denied"?"Las notificaciones están bloqueadas. Actívalas en Ajustes del dispositivo.":m==="unsupported"?"Este navegador no admite notificaciones push. Prueba Safari en iPhone o Chrome en Android.":"No se han podido activar las notificaciones.")}finally{setBusy(false)}}}>{busy?"Activando…":"Activar notificaciones"}</button><button className="later" onClick={close}>Ahora no</button></section></div>}
