"use client";
import {useEffect,useMemo,useState} from "react";


const SB="https://bwonxnayayopbohxuphs.supabase.co/storage/v1/object/public/Images";
const teamData=[{name:"Derio A",max:18,coach:"Nando Alonso",photo:SB+"/entrenadores/NandoAlonso.png"},{name:"Derio B",max:18,coach:"Gorka Barrio",photo:SB+"/entrenadores/GorkaBarrio.png"},{name:"Derio Fem",max:16,coach:"Iker Ibarluzea",photo:SB+"/entrenadores/IkerIbarluzea.png"},{name:"Derio Fem B",max:14,coach:"Ibai Mateos",photo:SB+"/entrenadores/IbaiMateos.png"},{name:"Juvenil A",max:18,coach:"Peio Garcia",photo:SB+"/entrenadores/PeioGarcia.png"},{name:"Juvenil B",max:18,coach:"Mikel Tara",photo:SB+"/entrenadores/MikelTara.png"}];
const teams=teamData.map(t=>t.name);
const coaches=["Nando Alonso","Gorka Barrio","Iker Ibarluzea","Ibai Mateos","Peio Garcia","Mikel Tara"];
const delegates=["Gabri Alzueta","Mikel Elejalde","Omar El Kabouri","Aner Taranilla","Koldo Corral","Asel Ibañez"];
type Season={positions:Record<string,string>,highest:string,lowest:string,firstCoach:string,coachCards:string,firstDelegate:string,delegateCards:string};
const empty:Season={positions:{},highest:"",lowest:"",firstCoach:"",coachCards:"",firstDelegate:"",delegateCards:""};

export default function Home(){
 const [name,setName]=useState(""); const [showSplash,setShowSplash]=useState(true); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [username,setUsername]=useState(""); const [register,setRegister]=useState(false); const [profileImage,setProfileImage]=useState<File|null>(null); const [notifications,setNotifications]=useState(false); const [rankMode,setRankMode]=useState<"general"|"jornada">("general"); const [step,setStep]=useState<"name"|"season"|"surprise"|"home">("name");
 useEffect(()=>{const splashTimer=window.setTimeout(()=>setShowSplash(false),1500);const saved=localStorage.getItem("quiniderio-player");if(saved){try{const x=JSON.parse(saved);if(x.name&&x.completed){setName(x.name);setDinio(x.dinio||"");if(x.season)setSeason(x.season);setStep("home")}}catch{}} fetch("/api/federation").then(r=>r.json()).then(d=>setFedGames(d.teams||[])).catch(()=>{});return()=>window.clearTimeout(splashTimer);},[]);
 const [season,setSeason]=useState<Season>(empty); const [fedGames,setFedGames]=useState<Array<{name:string,opponent?:string,status?:string,date?:string,time?:string,venue?:string,isHome?:boolean,federationRound?:number}>>([]); const [surprise,setSurprise]=useState<"intro"|"vote">("intro"); const [dinio,setDinio]=useState(""); const [toast,setToast]=useState(""); const [tab,setTab]=useState<"inicio"|"quiniela"|"pronosticos"|"clasificacion"|"mas">("inicio"); const [picks,setPicks]=useState<Record<string,string>>({}); const [quizRound,setQuizRound]=useState(1); const [savedRounds,setSavedRounds]=useState<Record<number,boolean>>({});
 useEffect(()=>{let startY=0;let armed=false;const onStart=(e:TouchEvent)=>{if(window.scrollY===0){startY=e.touches[0].clientY;armed=true}};const onEnd=(e:TouchEvent)=>{if(armed&&e.changedTouches[0].clientY-startY>75){setToast("Actualizando…");window.location.reload()}armed=false};window.addEventListener("touchstart",onStart,{passive:true});window.addEventListener("touchend",onEnd,{passive:true});return()=>{window.removeEventListener("touchstart",onStart);window.removeEventListener("touchend",onEnd)}} ,[]);
 const complete=useMemo(()=>teams.every(t=>season.positions[t])&&season.highest&&season.lowest&&season.firstCoach&&season.coachCards&&season.firstDelegate&&season.delegateCards,[season]);
 const select=(key:keyof Season,value:string)=>setSeason(s=>({...s,[key]:value}));
 const currentDone=teams.filter(team=>picks[`${quizRound}:${team}`]).length;
 if(showSplash) return <main className="appSplash"><img src={SB+"/branding/LogoApp.png"} alt="QuiniDerio"/><div className="splashPulse"/><small>QUINIDERIO</small></main>;
 if(step==="name") return <main className="authScreen"><Brand/><section className="authWrap"><div className="authLogo"><img src={SB+"/branding/LogoApp.png"} alt="QuiniDerio"/><p>LA QUINIELA DEL CD DERIO</p></div><form className="authForm" onSubmit={e=>{e.preventDefault();if(register){if(username.trim().length>=3){setName(username.trim());setStep("season")}}else if(email&&password){setName(email.split("@")[0]);setStep("season")}}}><div className="authTabs"><button type="button" className={!register?"active":""} onClick={()=>setRegister(false)}>Iniciar sesión</button><button type="button" className={register?"active":""} onClick={()=>setRegister(true)}>Registrarme</button></div><h1>{register?"Crea tu cuenta":"Bienvenido"}</h1><p>{register?"Completa tu perfil para empezar a jugar.":"Accede a tu cuenta de QuiniDerio."}</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@email.com" autoComplete="email"/></label><label>Contraseña<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" autoComplete={register?"new-password":"current-password"}/></label>{register&&<><label>Nombre de usuario<input required minLength={3} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Nombre que verán los demás"/></label><label className="profileUpload"><span>Imagen de perfil <small>Opcional</small></span><input type="file" accept="image/*" onChange={e=>setProfileImage(e.target.files?.[0]||null)}/><b>{profileImage?profileImage.name:"Elegir imagen"}</b></label><label className="notificationOpt"><input type="checkbox" checked={notifications} onChange={e=>setNotifications(e.target.checked)}/><span><b>Activar notificaciones</b><small>Avisos de jornadas y novedades. Las activaremos próximamente.</small></span></label></>}<button className="authContinue">{register?"Crear cuenta y continuar":"Entrar"}</button></form></section></main>;
 if(step==="season") { const done=teams.filter(t=>season.positions[t]).length+[season.highest,season.lowest,season.firstCoach,season.coachCards,season.firstDelegate,season.delegateCards].filter(Boolean).length; const total=12; return <main><Brand/><div className="setupProgress"><div><span>PREDICCIONES DE TEMPORADA</span><b>{done}/{total}</b></div><div className="progressTrack"><i style={{width:`${Math.round(done/total*100)}%`}}/></div></div><div className="seasonHead"><p className="eyebrow">ANTES DE EMPEZAR</p><h1>Tus predicciones</h1><p>Estas elecciones son para toda la temporada. Cuando las confirmes no podrás modificarlas.</p></div><section className="season">
 <div className="predictionIntro"><span className="stepBadge">01</span><h2>¿Dónde acabará cada Derio?</h2><p>Elige una posición para cada equipo. <strong>+20 puntos</strong> por cada posición exacta.</p></div><div className="positionCards">{teamData.map(t=><article className={"positionCard "+(season.positions[t.name]?"selected":"")} key={t.name}><div className="coachPhoto"><img src={t.photo} alt={`Entrenador ${t.coach}`} /></div><div className="clubInfo"><small>CD DERIO</small><h3>{t.name}</h3><p>{t.coach}</p></div><div className="positionPicker"><span>POSICIÓN FINAL</span><div className="rankGrid">{Array.from({length:t.max},(_,i)=>{const v=String(i+1);return <button type="button" aria-label={`${v}º de ${t.max}`} className={season.positions[t.name]===v?"active":""} key={v} onClick={()=>setSeason(s=>({...s,positions:{...s.positions,[t.name]:v}}))}>{v}<sup>º</sup></button>})}</div></div></article>)}</div>
 <div className="categoryLabel"><span className="stepBadge">02</span><div><b>Comparativa Derio</b><small>¿Quién terminará más arriba y más abajo?</small></div></div><Choice title="Derio que queda más arriba" points="+10" value={season.highest} options={teams} onChange={v=>select("highest",v)}/><Choice title="Derio que queda más abajo" points="+10" value={season.lowest} options={teams} onChange={v=>select("lowest",v)}/>
 <div className="categoryLabel"><span className="stepBadge">03</span><div><b>Entrenadores</b><small>Disciplina durante la temporada</small></div></div><Choice title="Primer entrenador expulsado" points="+15" value={season.firstCoach} options={coaches} onChange={v=>select("firstCoach",v)}/><Choice title="Entrenador con más tarjetas" points="+15" value={season.coachCards} options={coaches} onChange={v=>select("coachCards",v)}/>
 <div className="categoryLabel"><span className="stepBadge">04</span><div><b>Delegados</b><small>Las últimas predicciones antes de confirmar</small></div></div><Choice title="Primer delegado expulsado" points="+15" value={season.firstDelegate} options={delegates} onChange={v=>select("firstDelegate",v)}/><Choice title="Delegado con más tarjetas" points="+15" value={season.delegateCards} options={delegates} onChange={v=>select("delegateCards",v)}/>
 </section><div className="confirmDock"><div><b>{complete?"Todo listo":"Completa tus elecciones"}</b><small>{complete?"Podrás revisar antes de entrar":`${12-done} pendientes`}</small></div><button className="submit" disabled={!complete} onClick={()=>setStep("surprise")}>{complete?"Confirmar":"Continuar"}</button></div></main>; }
 if(step==="surprise") return <main><Brand/><div className="lockedBackdrop"><div className={"surprise "+(surprise==="vote"?"vote":"")}>{surprise==="intro"?<><div className="alertMark">!</div><p className="eyebrow">¡ESPERA!</p><h1>Falta la predicción<br/>más importante...</h1><button onClick={()=>setSurprise("vote")}>DIME</button></>:<><img className="dinioSupabase" src={SB+"/entrenadores/DinioDerio.png"} alt="Dinio"/><p className="eyebrow">ÚLTIMA PREDICCIÓN</p><h2>¿Se irá Dinio de Derio a lo largo de esta temporada?</h2><strong className="extra">+5 puntos extra</strong><div className="yesno"><button className={dinio==="SI"?"active":""} onClick={()=>setDinio("SI")}>SÍ</button><button className={dinio==="NO"?"active":""} onClick={()=>setDinio("NO")}>NO</button></div><button className="confirm" disabled={!dinio} onClick={()=>{localStorage.setItem("quiniderio-player",JSON.stringify({name,completed:true,dinio,season}));setStep("home")}}>Confirmar y entrar</button></>}</div></div></main>;
 return <main className="dashboard"><Brand avatar={name[0]?.toUpperCase()} name={name} onHome={()=>setTab("inicio")}/>{toast&&<div className="gameToast">{toast}</div>}{tab==="inicio"&&<HomeOverview name={name} currentDone={currentDone} onTab={setTab}/>} {tab==="quiniela"&&<GameQuiniela picks={picks} setPicks={setPicks} round={quizRound} setRound={setQuizRound} saved={!!savedRounds[quizRound]} onSave={()=>{setSavedRounds(v=>({...v,[quizRound]:true}));setToast("¡Quiniela guardada! ✓");setTimeout(()=>setToast(""),1800)}}/>} {tab==="pronosticos"&&<MyPredictions picks={picks} round={quizRound} onEdit={()=>setTab("quiniela")}/>} {tab==="clasificacion"&&<Ranking mode={rankMode} setMode={setRankMode}/>} {tab==="mas"&&<More name={name} dinio={dinio} season={season}/>}<nav className="liquidNav" aria-label="Navegación principal"><button aria-label="Inicio" className={tab==="inicio"?"active":""} onClick={()=>setTab("inicio")}><span className="navIcon"><HomeIcon/></span><small>Inicio</small></button><button aria-label="Quiniela" className={tab==="quiniela"?"active":""} onClick={()=>setTab("quiniela")}><span className="navIcon"><TargetIcon/></span><small>Quiniela</small></button><button aria-label="Mis pronósticos" className={tab==="pronosticos"?"active":""} onClick={()=>setTab("pronosticos")}><span className="navIcon"><UsersIcon/></span><small>Pronóst.</small></button><button aria-label="Clasificación" className={tab==="clasificacion"?"active":""} onClick={()=>setTab("clasificacion")}><span className="navIcon"><StandingsIcon/></span><small>Clasif.</small></button><button aria-label="Más" className={tab==="mas"?"active":""} onClick={()=>setTab("mas")}><span className="navIcon"><AccountIcon/></span><small>Más</small></button></nav></main>
}
function HomeOverview({name,currentDone,onTab}:{name:string,currentDone:number,onTab:(tab:"inicio"|"quiniela"|"pronosticos"|"clasificacion"|"mas")=>void}){
 const homeGames=teams.map(team=>({name:team,...(quizFixtures[1][team]||{})}));
 return <div className="qdHome">
  <aside className="qdSide">
   <div className="qdSideTitle">MENÚ</div>
   <button className="active" onClick={()=>onTab("inicio")}><HomeIcon/>Inicio</button>
   <button onClick={()=>onTab("quiniela")}><TargetIcon/>Quiniela</button>
   <button onClick={()=>onTab("pronosticos")}><UsersIcon/>Mis pronósticos</button>
   <button onClick={()=>onTab("clasificacion")}><StandingsIcon/>Clasificación</button>
   <button onClick={()=>onTab("mas")}><AccountIcon/>Mi cuenta</button>
   <div className="qdSeason"><small>TEMPORADA</small><b>2026/27</b></div>
  </aside>
  <div className="qdHomeMain">
   <section className="qdBanner">
    <img src="https://bwonxnayayopbohxuphs.supabase.co/storage/v1/object/public/Images/branding/Imagen%20con%20Fondo%20Eliminado.png" alt="QuiniDerio · CD Derio"/>
    <div className="qdBannerShade"/>
    <div className="qdBannerContent"><span><i/> TEMPORADA 2026/27</span><h1>QUINI<span>DERIO</span></h1><p>LA QUINIELA DEL CD DERIO</p></div>
   </section>
   <section className="qdSummary">
    <button className="qdAction" onClick={()=>onTab("quiniela")}><small>HAZ TU PRONÓSTICO</small><b>Jornada 1</b><span>Completa los 6 partidos de la jornada.</span><em>Ir a mi quiniela →</em></button>
    <article><small>ESTADO</small><b>{currentDone}/6</b><span>{currentDone===6?"Pronósticos completados":"Pronósticos realizados"}</span></article>
    <button onClick={()=>onTab("clasificacion")}><small>LÍDER ACTUAL</small><b>—</b><span>Clasificación general</span></button>
    <button onClick={()=>onTab("clasificacion")}><small>TU POSICIÓN</small><b>—</b><span>0 PTS</span></button>
   </section>
   <section className="qdRound">
    <div className="qdRoundHead"><div><h2>Jornada 1</h2><span>Temporada 2026/27</span></div><button onClick={()=>onTab("quiniela")}>Hacer quiniela →</button></div>
    <div className="qdRoundTabs">{[1,2,3,4,5,6,7,8].map(n=><span className={n===1?"active":""} key={n}>J{n}</span>)}</div>
    <div className="qdFixtureList">{homeGames.map(game=>{const rival=game.opponent||"Por confirmar";const home=game.isHome===false?rival:game.name;const away=game.isHome===false?game.name:rival;return <div className="qdFixture" key={game.name}><div className="qdClub home"><b>{home}</b><ClubCrest src={game.isHome===false?game.crest||rivalCrests[game.name]:"/derio-crest.svg"} name={home}/></div><div className="qdKick"><small>{game.date||"Fecha pendiente"}</small><strong>{game.time||"—"}</strong></div><div className="qdClub"><ClubCrest src={game.isHome===false?"/derio-crest.svg":game.crest||rivalCrests[game.name]} name={away}/><b>{away}</b></div></div>})}</div>
   </section>
  </div>
 </div>
}
function Brand({avatar,name,onHome}:{avatar?:string,name?:string,onHome?:()=>void}){return <header className="brandBar glassHeader"><div className="brandMark"><img src="https://bwonxnayayopbohxuphs.supabase.co/storage/v1/object/public/Images/branding/LogoApp.png" alt="QuiniDerio"/><div><b className="logo">Quini<span>Derio</span></b><small>LA QUINIELA DEL CD DERIO</small></div></div>{avatar&&<button type="button" className="avatar userChip" onClick={onHome} aria-label="Volver a Inicio"><span>{avatar}</span>{name&&<b>{name}</b>}</button>}</header>}
function Choice({title,points,value,options,onChange}:{title:string,points:string,value:string,options:string[],onChange:(v:string)=>void}){return <section className="choice"><span><b>{title}</b><em>{points}</em></span><div className="optionCards">{options.map(o=><button type="button" className={value===o?"active":""} onClick={()=>onChange(o)} key={o}><i>{o.split(" ").map(x=>x[0]).slice(0,2).join("")}</i><strong>{o}</strong><span>{value===o?"✓":"›"}</span></button>)}</div></section>}

type Fixture={name:string,opponent?:string,status?:string,date?:string,time?:string,venue?:string,isHome?:boolean,federationRound?:number,competition?:string,crest?:string};
// Confirmed directly from the club's federation screenshots; unknown times stay unknown.
const rivalCrests:Record<string,string>={
 "Derio A":"/aretxabaleta-crest.svg",
 "Derio Fem":"/intxaurdi-crest.svg",
 "Derio Fem B":"/ibaiondo-crest.svg",
 "Derio B":"/berango-b-crest.svg",
 "Juvenil A":"https://upload.wikimedia.org/wikipedia/commons/e/e4/Milan_Academy_%28AC_Milan%29.svg",
 "Juvenil B":"https://api.clupik.com/clubs/9604/images/clubTransparent.png"
};
const confirmedFixtures:Record<string,Partial<Fixture>>={
 "Derio A":{opponent:"Aretxabaleta U.D.",date:"26/09/2026",time:"12:00",venue:"Ibarra",isHome:false,federationRound:4,competition:"3ª RFEF"},
 "Derio B":{opponent:"Berango B",date:"27/09/2026",time:"16:15",isHome:false,federationRound:2,competition:"Liga Derio B"},
 "Derio Fem":{opponent:"Intxaurdi K.E.",date:"27/09/2026",time:"18:15",isHome:true,federationRound:2,competition:"Femenina Vasca"},
 "Derio Fem B":{opponent:"Ibaiondo Nerbioi A",date:"04/10/2026",time:"",isHome:false,federationRound:1,competition:"1ª Regional"},
 "Juvenil A":{opponent:"MSC Butroe",date:"27/09/2026",time:"15:45",isHome:true,federationRound:2,competition:"Liga Juvenil A"},
 "Juvenil B":{opponent:"Leioa D",date:"04/10/2026",time:"",isHome:true,federationRound:2,competition:"Liga Juvenil B"}
};
const quizFixtures:Record<number,Record<string,Partial<Fixture>>>={
 1:{"Derio A":confirmedFixtures["Derio A"],"Derio B":confirmedFixtures["Derio B"],"Derio Fem":confirmedFixtures["Derio Fem"],"Derio Fem B":{opponent:"Bizkerre C",date:"26/09/2026",time:"18:30",isHome:true,competition:"Amistoso",crest:"https://pbs.twimg.com/profile_images/1612424888668635136/6IixKALc.jpg"},"Juvenil A":confirmedFixtures["Juvenil A"],"Juvenil B":{opponent:"Sestao River",date:"26/09/2026",time:"16:00",isHome:true,competition:"Amistoso",crest:"https://pbs.twimg.com/profile_images/1898675328312078378/KMMAP-Rd.jpg"}},
 2:{"Derio Fem B":confirmedFixtures["Derio Fem B"],"Juvenil B":confirmedFixtures["Juvenil B"]},
 3:{}
};
function GameQuiniela({picks,setPicks,round,setRound,saved,onSave}:{picks:Record<string,string>,setPicks:(value:Record<string,string>|((prev:Record<string,string>)=>Record<string,string>))=>void,round:number,setRound:(round:number)=>void,saved:boolean,onSave:()=>void}){
 const games=teams.map(team=>({name:team,...(quizFixtures[round][team]||{})}));
 const done=teams.filter(team=>picks[`${round}:${team}`]).length;
 const pending=games.filter(game=>!game.opponent).length;
 return <section className="tabPage">
  <div className="pageTop compactTop"><div className="roundBadge"><i/> {round===1?"JORNADA ABIERTA":"PRÓXIMAMENTE"}</div><h1>Tu quiniela</h1><p>Toca 1, X o 2 en cada partido.</p></div>
  <div className="quizRounds" role="group" aria-label="Jornadas de la quiniela">{[1,2,3].map(n=><button type="button" key={n} aria-pressed={round===n} className={round===n?"active":""} onClick={()=>setRound(n)}>Jornada {n}</button>)}</div>
  <div className={"roundProgress "+(done===6?"complete":"")}><b>{done}/6</b><div><i style={{width:`${done/6*100}%`}}/></div><span>{done===6?"¡Jornada completada!":"Te faltan "+(6-done)+" pronósticos"}</span></div>
  {done===6&&<div className="completeBanner"><span>✓</span><div><b>¡Pleno de pronósticos!</b><small>Ya puedes guardar tu quiniela.</small></div></div>}
  <div className="matchStack">{games.map((game,i)=>{
   const {name:team,date="",time="",venue="",federationRound,competition}=game;
   const rival=game.opponent||"Rival por confirmar";
   const isHome=game.isHome!==false;
   const home=isHome?team:rival,away=isHome?rival:team;
   const label=competition==="Amistoso"?"AMISTOSO":federationRound?`${competition||"Liga"} · Jornada ${federationRound}`:`JORNADA DE LIGA PENDIENTE`;
   const pickKey=`${round}:${team}`;
   return <article className={"matchCard "+(picks[pickKey]?"picked":"")} key={team}>
    <div className="matchMeta"><span>{label}</span><em><i className="lockDot"/> {time?"Cierra 1h antes":"Hora pendiente"}</em></div>
    <div className="fixtureInfo"><span>{date?`${date} · ${time||"Hora por confirmar"}`:competition==="Amistoso"?"Este fin de semana · Hora por confirmar":"Fecha por confirmar"}</span><span>{game.isHome===undefined?"Localía y campo por confirmar":`${isHome?"Local":"Visitante"} · ${isHome?"Ibaiondo, Derio":venue||"Campo por confirmar"}`}</span></div>
    <div className="versus"><div><ClubCrest src={isHome?"/derio-crest.svg":game.crest||rivalCrests[team]} name={home}/><b>{home}</b><small>{game.isHome===undefined?"DERIO":"LOCAL"}</small></div><strong>VS</strong><div><ClubCrest src={isHome?game.crest||rivalCrests[team]:"/derio-crest.svg"} name={away}/><b>{away}</b><small>{game.isHome===undefined?"POR CONFIRMAR":"VISITANTE"}</small></div></div>
    <div className="pickHint">ELIGE TU PRONÓSTICO</div>
    <div className="oneXtwo">{["1","X","2"].map(x=><button disabled={saved||!game.opponent} aria-label={`${x}: ${x==="1"?`gana ${home}`:x==="X"?"empate":`gana ${away}`}`} aria-pressed={picks[pickKey]===x} className={picks[pickKey]===x?"active":""} onClick={()=>setPicks(v=>({...v,[pickKey]:x}))} key={x}><b>{x}</b><small>{x==="1"?"LOCAL":x==="X"?"EMPATE":"VISITANTE"}</small></button>)}</div>
    {picks[pickKey]&&<div className="pickFeedback">Pronóstico: <b>{picks[pickKey]}</b><span>Guardado localmente</span></div>}
   </article>
  })}</div>
  <div className="roundDock"><div><b>{saved?"Quiniela guardada":done===6?"Lista para guardar":done+"/6 elegidos"}</b><small>{saved?"Tus pronósticos quedan bloqueados en este prototipo":pending?`Pendientes ${pending} rivales por confirmar`:done===6?"Revisa tus elecciones":"Completa todos los partidos"}</small></div><button className={saved?"saved":""} disabled={done<6||saved||pending>0} onClick={onSave}>{saved?"✓ Guardada":"Guardar"}</button></div>
 </section>
}
function DinioImage(){const [failed,setFailed]=useState(false);return failed?<div className="dinioFallback" role="img" aria-label="Imagen de Dinio pendiente"><img src="/derio-crest.svg" alt=""/><strong>DINIO</strong></div>:<img src="/dinio.png" alt="Dinio y CD Derio" onError={()=>setFailed(true)}/>;}
function QuiniCover(){return <section className="quiniCover uploadedCover" aria-label="QuiniDerio"><img src={QUINIDERIO_COVER} alt="QuiniDerio · CD Derio" style={{display:"block",width:"100%",height:"auto",objectFit:"cover"}}/></section>}
function CoachesPanel(){return <section className="coachesPanel"><div className="coachesIntro"><ClubCrest src="/derio-crest.svg" name="CD Derio"/><div><p className="eyebrow">CD DERIO</p><h2>El equipo</h2><small>Entrenadores de la temporada</small></div></div><div className="coachGrid">{teamData.map(t=><article key={t.name}><div className="coachAvatar"><img src={t.photo} alt={`Entrenador ${t.coach}`} /></div><b>{t.coach}</b><small>{t.name}</small></article>)}</div></section>}
function ClubCrest({src,name}:{src?:string,name:string}){return src?<span className="crestBox"><img src={src} alt={`Escudo de ${name}`} loading="lazy"/></span>:<i aria-hidden="true">?</i>}
function MyPredictions({picks,round,onEdit}:{picks:Record<string,string>,round:number,onEdit:()=>void}){const total=teams.filter(team=>picks[`${round}:${team}`]).length;return <section className="tabPage"><div className="pageTop porraPageTop"><p className="eyebrow">MIS PRONÓSTICOS</p><h1>Tu jornada</h1><p>Consulta tus elecciones y las de tus rivales.</p></div><div className="predictionSummary"><div><small>COMPLETADOS</small><b>{total}<em>/6</em></b></div><span>{total===6?"Jornada completa ✓":"Te faltan "+(6-total)}</span></div><div className="myPicks">{teams.map((team,i)=><button type="button" className="myPick" onClick={onEdit} aria-label={`Ver partido y pronóstico de ${team}`} key={team}><span>{i+1}</span><div><b>{team}</b><small>Jornada {round} · tocar para ver</small></div><strong className={picks[`${round}:${team}`]?"hasPick":""}>{picks[`${round}:${team}`]||"—"}</strong></button>)}</div><section className="rivalsPanel"><div><p className="eyebrow">COMPARTE LA JORNADA</p><h2>Pronósticos de tus rivales</h2><p>Cuando los demás jugadores los publiquen, podrás comparar aquí sus elecciones partido a partido.</p></div><button type="button" onClick={()=>alert("Los pronósticos de los rivales aparecerán al publicarse la jornada.")}>Ver rivales</button></section></section>}
function Ranking({mode,setMode}:{mode:"general"|"jornada",setMode:(m:"general"|"jornada")=>void}){return <section className="tabPage"><div className="pageTop porraPageTop"><p className="eyebrow">CLASIFICACIÓN</p><h1>{mode==="general"?"Clasificación general":"Clasificación de jornada"}</h1><p>{mode==="general"?"Puntos acumulados durante la temporada.":"Puntos conseguidos en la jornada actual."}</p></div><div className="rankingTabs"><button className={mode==="general"?"active":""} onClick={()=>setMode("general")}>General</button><button className={mode==="jornada"?"active":""} onClick={()=>setMode("jornada")}>Jornada</button></div><div className="leaderCard"><div><span>1</span><div><b>Sin líder aún</b><small>La clasificación aparecerá con las primeras puntuaciones</small></div><strong>0 <em>pts</em></strong></div></div><div className="rankingHeader"><span>#</span><span>JUGADOR</span><span>PTS</span></div><div className="rankingEmpty porraEmpty">Todavía no hay puntuaciones registradas.</div></section>}
function More({name,dinio,season}:{name:string,dinio:string,season:Season}){
 const [panel,setPanel]=useState<"season"|"extra"|"rules"|null>(null);
 useEffect(()=>{if(!panel)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setPanel(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[panel]);
 const predictions=[...teamData.map(team=>[team.name,season.positions[team.name]?`${season.positions[team.name]}º`:"—"]),["Derio más arriba",season.highest||"—"],["Derio más abajo",season.lowest||"—"],["Primer entrenador expulsado",season.firstCoach||"—"],["Entrenador con más tarjetas",season.coachCards||"—"],["Primer delegado expulsado",season.firstDelegate||"—"],["Delegado con más tarjetas",season.delegateCards||"—"]];
 return <section className="tabPage profilePage"><div className="pageTop"><p className="eyebrow">TU PERFIL</p><h1>{name}</h1><p>Temporada QuiniDerio 2026/27</p></div><div className="profileCard"><div className="bigAvatar">{name[0]}</div><div><b>{name}</b><small>Jugador QuiniDerio</small></div><strong>0 pts</strong></div><div className="menuCards"><button type="button" onClick={()=>setPanel("season")}><span><TargetIcon/></span><div><b>Mis predicciones</b><small>Consulta tus elecciones de temporada</small></div><em>›</em></button><button type="button" onClick={()=>setPanel("extra")}><span><UsersIcon/></span><div><b>Predicción extra</b><small>Dinio: {dinio||"—"}</small></div><em>›</em></button><button type="button" onClick={()=>setPanel("rules")}><span><StandingsIcon/></span><div><b>Cómo se puntúa</b><small>Reglas y sistema de puntos</small></div><em>›</em></button><button type="button" className="resetAccount" onClick={()=>{if(window.confirm("¿Reiniciar la cuenta de prueba? Se borrarán de este dispositivo el perfil, las predicciones y el progreso guardado.")){localStorage.removeItem("quiniderio-player");sessionStorage.clear();window.location.reload();}}}><span>↻</span><div><b>Reiniciar cuenta</b><small>Solo para pruebas · borra el progreso de este dispositivo</small></div><em>›</em></button></div>{panel&&<div className="detailBackdrop" onClick={()=>setPanel(null)}><section role="dialog" aria-modal="true" aria-label={panel==="season"?"Mis predicciones":panel==="extra"?"Predicción extra":"Cómo se puntúa"} className="detailSheet" onClick={event=>event.stopPropagation()}><div className="detailSheetHead"><div><small>QUINIDERIO · 2026/27</small><h2>{panel==="season"?"Mis predicciones":panel==="extra"?"Predicción extra":"Cómo se puntúa"}</h2></div><button type="button" aria-label="Cerrar" onClick={()=>setPanel(null)}>×</button></div>{panel==="season"&&<div className="detailRows">{predictions.map(([label,value])=><div className="detailRow" key={label}><span>{label}</span><b>{value}</b></div>)}</div>}{panel==="extra"&&<div className="detailExtra"><p>¿Se irá Dinio de Derio esta temporada?</p><strong>{dinio||"Sin respuesta guardada"}</strong><small>Predicción confirmada · +5 puntos si aciertas</small></div>}{panel==="rules"&&<div className="detailRows">{[["Quiniela semanal","+1 punto por acierto"],["Posición final exacta","+20 puntos por equipo"],["Derio más arriba o abajo","+10 puntos cada uno"],["Entrenadores y delegados","+15 puntos por acierto"],["Predicción extra de Dinio","+5 puntos por acierto"]].map(([label,value])=><div className="detailRow" key={label}><span>{label}</span><b>{value}</b></div>)}</div>}</section></div>}</section>
}
function HomeIcon(){return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M3 10.5 12 3l9 7.5V21h-6v-6H9v6H3Z"/></svg>}
function TargetIcon(){return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M12 3a9 9 0 1 0 9 9"/><path d="M12 7a5 5 0 1 0 5 5"/><path d="M12 11a1 1 0 1 0 1 1"/><path d="m14.5 9.5 5-5"/><path d="M17 4.5h2.5V7"/></svg>}
function UsersIcon(){return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="8" cy="8" r="3"/><circle cx="16" cy="8" r="3"/><path d="M2.5 20v-1.5A4.5 4.5 0 0 1 7 14h2a4.5 4.5 0 0 1 4.5 4.5V20M14 14h1.5a4 4 0 0 1 4 4V20"/></svg>}
function StandingsIcon(){return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M4 20V10h4v10M10 20V4h4v16M16 20v-7h4v7M2 20h20"/></svg>}
function AccountIcon(){return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>}
