"use client";
import {useEffect,useMemo,useState} from "react";

const teams=["Derio A","Derio B","Derio Fem","Derio Fem B","Juvenil A","Juvenil B"];
const coaches=["Nando Alonso","Gorka Barrio","Iker Ibarluzea","Ibai Mateos","Peio Garcia","Mikel Taranilla"];
const delegates=["Gabri Alzueta","Mikel Elejalde","Omar El Kabouri","Aner Taranilla","Koldo Corral","Asel Ibañez"];
type Season={positions:Record<string,string>,highest:string,lowest:string,firstCoach:string,coachCards:string,firstDelegate:string,delegateCards:string};
const empty:Season={positions:{},highest:"",lowest:"",firstCoach:"",coachCards:"",firstDelegate:"",delegateCards:""};

export default function Home(){
 const [name,setName]=useState(""); const [step,setStep]=useState<"name"|"season"|"surprise"|"home">("name");\n useEffect(()=>{const saved=localStorage.getItem("quiniderio-player");if(saved){try{const x=JSON.parse(saved);if(x.name&&x.completed){setName(x.name);setDinio(x.dinio||"");setStep("home")}}catch{}}},[]);
 const [season,setSeason]=useState<Season>(empty); const [surprise,setSurprise]=useState<"intro"|"vote">("intro"); const [dinio,setDinio]=useState("");
 const complete=useMemo(()=>teams.every(t=>season.positions[t])&&season.highest&&season.lowest&&season.firstCoach&&season.coachCards&&season.firstDelegate&&season.delegateCards,[season]);
 const select=(key:keyof Season,value:string)=>setSeason(s=>({...s,[key]:value}));
 if(step==="name") return <main className="welcome"><Brand/><section className="hero"><div><p className="eyebrow">BIENVENIDO</p><h1>Entra en QuiniDerio</h1><p>Identifícate para hacer tus predicciones de la temporada.</p></div></section><form className="identity" onSubmit={e=>{e.preventDefault();if(name.trim().split(/\s+/).length>=2)setStep("season")}}><label>Nombre y apellido</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Gabri Alzueta"/><button disabled={name.trim().split(/\s+/).length<2}>Continuar</button></form></main>;
 if(step==="season") return <main><Brand/><div className="seasonHead"><p className="eyebrow">ANTES DE EMPEZAR</p><h1>Tus predicciones</h1><p>Estas elecciones son para toda la temporada. Cuando las confirmes no podrás modificarlas.</p></div><section className="season">
 <h2>Posición final <span>+20 por acierto</span></h2>{teams.map(t=><label className="row" key={t}><b>{t}</b><input type="number" min="1" max="30" inputMode="numeric" placeholder="Pos." value={season.positions[t]||""} onChange={e=>setSeason(s=>({...s,positions:{...s.positions,[t]:e.target.value}}))}/></label>)}
 <Choice title="Derio que queda más arriba" points="+10" value={season.highest} options={teams} onChange={v=>select("highest",v)}/><Choice title="Derio que queda más abajo" points="+10" value={season.lowest} options={teams} onChange={v=>select("lowest",v)}/>
 <Choice title="Primer entrenador expulsado" points="+15" value={season.firstCoach} options={coaches} onChange={v=>select("firstCoach",v)}/><Choice title="Entrenador con más tarjetas" points="+15" value={season.coachCards} options={coaches} onChange={v=>select("coachCards",v)}/>
 <Choice title="Primer delegado expulsado" points="+15" value={season.firstDelegate} options={delegates} onChange={v=>select("firstDelegate",v)}/><Choice title="Delegado con más tarjetas" points="+15" value={season.delegateCards} options={delegates} onChange={v=>select("delegateCards",v)}/>
 </section><button className="submit" disabled={!complete} onClick={()=>setStep("surprise")}>Confirmar predicciones</button></main>;
 if(step==="surprise") return <main><Brand/><div className="lockedBackdrop"><div className={"surprise "+(surprise==="vote"?"vote":"")}>{surprise==="intro"?<><div className="alertMark">!</div><p className="eyebrow">¡ESPERA!</p><h1>Falta la predicción<br/>más importante...</h1><button onClick={()=>setSurprise("vote")}>DIME</button></>:<><img src="/dinio.png" alt="Dinio y CD Derio"/><p className="eyebrow">ÚLTIMA PREDICCIÓN</p><h2>¿Se irá Dinio de Derio a lo largo de esta temporada?</h2><strong className="extra">+5 puntos extra</strong><div className="yesno"><button className={dinio==="SI"?"active":""} onClick={()=>setDinio("SI")}>SÍ</button><button className={dinio==="NO"?"active":""} onClick={()=>setDinio("NO")}>NO</button></div><button className="confirm" disabled={!dinio} onClick={()=>{localStorage.setItem("quiniderio-player",JSON.stringify({name,completed:true,dinio}));setStep("home")}}>Confirmar y entrar</button></>}</div></div></main>;
 return <main className="dashboard"><Brand avatar={name[0]?.toUpperCase()}/><section className="hero"><div><p className="eyebrow">PRÓXIMA QUINIELA</p><h1>Este fin de semana</h1><p>Los partidos aparecerán automáticamente con su posición y se bloquearán 1 hora antes.</p></div><div className="miniScore"><strong>0</strong><small>puntos</small></div></section><section className="dashGrid"><article><small>MI POSICIÓN</small><strong>—</strong><span>La clasificación empieza con los primeros aciertos</span></article><article><small>PREDICCIONES</small><strong>0/6</strong><span>Partidos disponibles esta jornada</span></article></section><div className="sectionTitle"><h2>Quiniela semanal</h2><span>1 · X · 2</span></div><div className="emptyCard"><div className="ball">●</div><b>Preparando los partidos</b><p>Estamos conectando los calendarios de los seis equipos con Federación.</p></div><nav><button className="active">⌂<small>Inicio</small></button><button>✓<small>Quiniela</small></button><button>▥<small>Clasificación</small></button><button>•••<small>Más</small></button></nav></main>
}
function Brand({avatar}:{avatar?:string}){return <header><div><b className="logo">Quini<span>Derio</span></b><small>La quiniela del CD Derio</small></div>{avatar&&<div className="avatar">{avatar}</div>}</header>}
function Choice({title,points,value,options,onChange}:{title:string,points:string,value:string,options:string[],onChange:(v:string)=>void}){return <label className="choice"><span><b>{title}</b><em>{points}</em></span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Selecciona...</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
