"use client";
import {useEffect,useMemo,useState} from "react";

const teamData=[{name:"Derio A",max:18,coach:"Nando Alonso"},{name:"Derio B",max:18,coach:"Gorka Barrio"},{name:"Derio Fem",max:16,coach:"Iker Ibarluzea"},{name:"Derio Fem B",max:14,coach:"Ibai Mateos"},{name:"Juvenil A",max:18,coach:"Peio Garcia"},{name:"Juvenil B",max:18,coach:"Mikel Taranilla"}];
const teams=teamData.map(t=>t.name);
const coaches=["Nando Alonso","Gorka Barrio","Iker Ibarluzea","Ibai Mateos","Peio Garcia","Mikel Taranilla"];
const delegates=["Gabri Alzueta","Mikel Elejalde","Omar El Kabouri","Aner Taranilla","Koldo Corral","Asel Ibañez"];
type Season={positions:Record<string,string>,highest:string,lowest:string,firstCoach:string,coachCards:string,firstDelegate:string,delegateCards:string};
const empty:Season={positions:{},highest:"",lowest:"",firstCoach:"",coachCards:"",firstDelegate:"",delegateCards:""};

export default function Home(){
 const [name,setName]=useState(""); const [step,setStep]=useState<"name"|"season"|"surprise"|"home">("name");
 useEffect(()=>{const saved=localStorage.getItem("quiniderio-player");if(saved){try{const x=JSON.parse(saved);if(x.name&&x.completed){setName(x.name);setDinio(x.dinio||"");setStep("home")}}catch{}} fetch("/api/federation").then(r=>r.json()).then(d=>setFedGames(d.teams||[])).catch(()=>{});},[]);
 const [season,setSeason]=useState<Season>(empty); const [fedGames,setFedGames]=useState<Array<{name:string,opponent?:string,status?:string}>>([]); const [surprise,setSurprise]=useState<"intro"|"vote">("intro"); const [dinio,setDinio]=useState(""); const [toast,setToast]=useState(""); const [tab,setTab]=useState<"inicio"|"quiniela"|"clasificacion"|"mas">("inicio"); const [picks,setPicks]=useState<Record<string,string>>({}); const [savedRound,setSavedRound]=useState(false);
 const complete=useMemo(()=>teams.every(t=>season.positions[t])&&season.highest&&season.lowest&&season.firstCoach&&season.coachCards&&season.firstDelegate&&season.delegateCards,[season]);
 const select=(key:keyof Season,value:string)=>setSeason(s=>({...s,[key]:value}));
 if(step==="name") return <main className="welcome"><Brand/><section className="hero"><div><p className="eyebrow">BIENVENIDO</p><h1>Entra en QuiniDerio</h1><p>Identifícate para hacer tus predicciones de la temporada.</p></div></section><form className="identity" onSubmit={e=>{e.preventDefault();if(name.trim().split(/\s+/).length>=2)setStep("season")}}><label>Nombre y apellido</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Gabri Alzueta"/><button disabled={name.trim().split(/\s+/).length<2}>Continuar</button></form></main>;
 if(step==="season") { const done=teams.filter(t=>season.positions[t]).length+[season.highest,season.lowest,season.firstCoach,season.coachCards,season.firstDelegate,season.delegateCards].filter(Boolean).length; const total=12; return <main><Brand/><div className="setupProgress"><div><span>PREDICCIONES DE TEMPORADA</span><b>{done}/{total}</b></div><div className="progressTrack"><i style={{width:`${Math.round(done/total*100)}%`}}/></div></div><div className="seasonHead"><p className="eyebrow">ANTES DE EMPEZAR</p><h1>Tus predicciones</h1><p>Estas elecciones son para toda la temporada. Cuando las confirmes no podrás modificarlas.</p></div><section className="season">
 <div className="predictionIntro"><span className="stepBadge">01</span><h2>¿Dónde acabará cada Derio?</h2><p>Elige una posición para cada equipo. <strong>+20 puntos</strong> por cada posición exacta.</p></div><div className="positionCards">{teamData.map(t=><article className={"positionCard "+(season.positions[t.name]?"selected":"")} key={t.name}><div className="coachPhoto"><span>{t.coach.split(" ").map(x=>x[0]).slice(0,2).join("")}</span></div><div className="clubInfo"><small>CD DERIO</small><h3>{t.name}</h3><p>{t.coach}</p></div><div className="positionPicker"><span>POSICIÓN FINAL</span><div className="rankGrid">{Array.from({length:t.max},(_,i)=>{const v=String(i+1);return <button type="button" aria-label={`${v}º de ${t.max}`} className={season.positions[t.name]===v?"active":""} key={v} onClick={()=>setSeason(s=>({...s,positions:{...s.positions,[t.name]:v}}))}>{v}<sup>º</sup></button>})}</div></div></article>)}</div>
 <div className="categoryLabel"><span className="stepBadge">02</span><div><b>Comparativa Derio</b><small>¿Quién terminará más arriba y más abajo?</small></div></div><Choice title="Derio que queda más arriba" points="+10" value={season.highest} options={teams} onChange={v=>select("highest",v)}/><Choice title="Derio que queda más abajo" points="+10" value={season.lowest} options={teams} onChange={v=>select("lowest",v)}/>
 <div className="categoryLabel"><span className="stepBadge">03</span><div><b>Entrenadores</b><small>Disciplina durante la temporada</small></div></div><Choice title="Primer entrenador expulsado" points="+15" value={season.firstCoach} options={coaches} onChange={v=>select("firstCoach",v)}/><Choice title="Entrenador con más tarjetas" points="+15" value={season.coachCards} options={coaches} onChange={v=>select("coachCards",v)}/>
 <div className="categoryLabel"><span className="stepBadge">04</span><div><b>Delegados</b><small>Las últimas predicciones antes de confirmar</small></div></div><Choice title="Primer delegado expulsado" points="+15" value={season.firstDelegate} options={delegates} onChange={v=>select("firstDelegate",v)}/><Choice title="Delegado con más tarjetas" points="+15" value={season.delegateCards} options={delegates} onChange={v=>select("delegateCards",v)}/>
 </section><div className="confirmDock"><div><b>{complete?"Todo listo":"Completa tus elecciones"}</b><small>{complete?"Podrás revisar antes de entrar":`${12-done} pendientes`}</small></div><button className="submit" disabled={!complete} onClick={()=>setStep("surprise")}>{complete?"Confirmar":"Continuar"}</button></div></main>; }
 if(step==="surprise") return <main><Brand/><div className="lockedBackdrop"><div className={"surprise "+(surprise==="vote"?"vote":"")}>{surprise==="intro"?<><div className="alertMark">!</div><p className="eyebrow">¡ESPERA!</p><h1>Falta la predicción<br/>más importante...</h1><button onClick={()=>setSurprise("vote")}>DIME</button></>:<><img src="/dinio.png" alt="Dinio y CD Derio"/><p className="eyebrow">ÚLTIMA PREDICCIÓN</p><h2>¿Se irá Dinio de Derio a lo largo de esta temporada?</h2><strong className="extra">+5 puntos extra</strong><div className="yesno"><button className={dinio==="SI"?"active":""} onClick={()=>setDinio("SI")}>SÍ</button><button className={dinio==="NO"?"active":""} onClick={()=>setDinio("NO")}>NO</button></div><button className="confirm" disabled={!dinio} onClick={()=>{localStorage.setItem("quiniderio-player",JSON.stringify({name,completed:true,dinio}));setStep("home")}}>Confirmar y entrar</button></>}</div></div></main>;
 return <main className="dashboard"><Brand avatar={name[0]?.toUpperCase()}/>{toast&&<div className="gameToast">{toast}</div>}{tab==="inicio"&&<><section className="porraHero"><div><div className="livePill"><i/> JORNADA ABIERTA</div><p className="eyebrow">TU JORNADA</p><h1>Haz tu quiniela</h1><p>6 partidos. Elige 1, X o 2 antes del cierre.</p><div className="heroActions"><button onClick={()=>setTab("quiniela")}>Empezar quiniela <span>→</span></button><small>+1 punto por acierto</small></div></div><div className="porraScore"><small>MIS PUNTOS</small><strong>0</strong><span>General · —</span></div></section><div className="quickStatus"><span><i/> EN JUEGO</span><b>Temporada 26/27</b><small>Actualización automática</small></div><section className="porraStats"><button onClick={()=>setTab("clasificacion")}><small>POSICIÓN</small><b>—</b><span>Ver clasificación ›</span></button><button onClick={()=>setTab("quiniela")}><small>PRONÓSTICOS</small><b>{Object.keys(picks).length}<em>/6</em></b><span>{Object.keys(picks).length===6?"Completada ✓":"Continuar ›"}</span></button></section><section className="porraNotice"><span>i</span><div><b>Jornada abierta</b><small>Puedes modificar cada pronóstico hasta 1 hora antes de su partido.</small></div></section><div className="homeDivider"><span>JUEGA · SUMA · ESCALA</span></div><div className="sectionTitle"><div><small>TU RETO</small><h2>Quiniela semanal</h2></div><span className="pointsPill">+6 pts máx.</span></div><button className="weeklyShortcut" onClick={()=>setTab("quiniela")}><div className="shortcutIcon">1X2</div><div><b>Ir a la quiniela</b><small>Completa tus 6 pronósticos</small></div><span>→</span></button></>}{tab==="quiniela"&&<GameQuiniela federation={fedGames} picks={picks} setPicks={setPicks} saved={savedRound} onSave={()=>{setSavedRound(true);setToast("¡Quiniela guardada! ✓");setTimeout(()=>setToast(""),1800)}}/>} {tab==="clasificacion"&&<Ranking/>} {tab==="mas"&&<More name={name} dinio={dinio}/>}<nav aria-label="Navegación principal"><button aria-label="Inicio" className={tab==="inicio"?"active":""} onClick={()=>setTab("inicio")}><span className="navIcon">⌂</span><small>Inicio</small></button><button aria-label="Quiniela" className={tab==="quiniela"?"active":""} onClick={()=>setTab("quiniela")}><span className="navIcon">1X2</span><small>Quiniela</small></button><button aria-label="Clasificación" className={tab==="clasificacion"?"active":""} onClick={()=>setTab("clasificacion")}><span className="navIcon">▥</span><small>Clasificación</small></button><button aria-label="Más" className={tab==="mas"?"active":""} onClick={()=>setTab("mas")}><span className="navIcon">•••</span><small>Más</small></button></nav></main>
}
function Brand({avatar}:{avatar?:string}){return <header className="brandBar"><div className="brandMark"><img src="/quiniderio-logo.jpg" alt="QuiniDerio"/><div><b className="logo">Quini<span>Derio</span></b><small>LA QUINIELA DEL CD DERIO</small></div></div>{avatar&&<div className="avatar">{avatar}</div>}</header>}
function Choice({title,points,value,options,onChange}:{title:string,points:string,value:string,options:string[],onChange:(v:string)=>void}){return <section className="choice"><span><b>{title}</b><em>{points}</em></span><div className="optionCards">{options.map(o=><button type="button" className={value===o?"active":""} onClick={()=>onChange(o)} key={o}><i>{o.split(" ").map(x=>x[0]).slice(0,2).join("")}</i><strong>{o}</strong><span>{value===o?"✓":"›"}</span></button>)}</div></section>}

function GameQuiniela({federation,picks,setPicks,saved,onSave}:{federation:Array<{name:string,opponent?:string,status?:string}>,picks:Record<string,string>,setPicks:(value:Record<string,string>|((prev:Record<string,string>)=>Record<string,string>))=>void,saved:boolean,onSave:()=>void}){const fallback=[["Derio A","Rival por confirmar"],["Derio B","Rival por confirmar"],["Derio Fem","Rival por confirmar"],["Derio Fem B","Rival por confirmar"],["Juvenil A","Rival por confirmar"],["Juvenil B","Rival por confirmar"]];const games=fallback.map(([team,rival])=>{const f=federation.find(x=>x.name===team);return [team,f?.opponent||rival]});const done=Object.keys(picks).length;return <section className="tabPage"><div className="pageTop compactTop"><div className="roundBadge"><i/> JORNADA ABIERTA</div><h1>Tu quiniela</h1><p>Toca 1, X o 2 en cada partido.</p></div><div className={"roundProgress "+(done===6?"complete":"")}><b>{done}/6</b><div><i style={{width:`${done/6*100}%`}}/></div><span>{done===6?"¡Jornada completada!":"Te faltan "+(6-done)+" pronósticos"}</span></div>{done===6&&<div className="completeBanner"><span>✓</span><div><b>¡Pleno de pronósticos!</b><small>Ya puedes guardar tu quiniela.</small></div></div>}<div className="matchStack">{games.map(([team,rival],i)=><article className={"matchCard "+(picks[team]?"picked":"")} key={team}><div className="matchMeta"><span>PARTIDO {i+1}</span><em><i className="lockDot"/> Cierra 1h antes</em></div><div className="versus"><div><i>CD</i><b>{team}</b><small>Pos. —</small></div><strong>VS</strong><div><i>?</i><b>{rival}</b><small>Pos. —</small></div></div><div className="pickHint">ELIGE TU PRONÓSTICO</div><div className="oneXtwo">{["1","X","2"].map(x=><button disabled={saved} aria-pressed={picks[team]===x} className={picks[team]===x?"active":""} onClick={()=>{setPicks(v=>({...v,[team]:x}))}} key={x}><b>{picks[team]===x?"✓ "+x:x}</b><small>{x==="1"?"LOCAL":x==="X"?"EMPATE":"VISITANTE"}</small></button>)}</div>{picks[team]&&<div className="pickFeedback">Pronóstico: <b>{picks[team]}</b><span>Guardado localmente</span></div>}</article>)}</div><div className="roundDock"><div><b>{saved?"Quiniela enviada":done===6?"Lista para guardar":done+"/6 elegidos"}</b><small>{saved?"Tus pronósticos quedan bloqueados en este prototipo":done===6?"Revisa tus elecciones":"Completa todos los partidos"}</small></div><button className={saved?"saved":""} disabled={done<6||saved} onClick={onSave}>{saved?"✓ Guardada":"Guardar"}</button></div></section>}
function Ranking(){return <section className="tabPage"><div className="pageTop porraPageTop"><p className="eyebrow">CLASIFICACIÓN</p><h1>Clasificación general</h1><p>Puntos acumulados durante la temporada.</p></div><div className="rankingTabs"><button className="active">General</button><button>Jornada</button></div><div className="leaderCard"><div><span>1</span><div><b>Sin líder aún</b><small>La clasificación aparecerá con las primeras puntuaciones</small></div><strong>0 <em>pts</em></strong></div></div><div className="rankingHeader"><span>#</span><span>JUGADOR</span><span>PTS</span></div><div className="rankingEmpty porraEmpty">Todavía no hay puntuaciones registradas.</div></section>}
function More({name,dinio}:{name:string,dinio:string}){return <section className="tabPage"><div className="pageTop"><p className="eyebrow">TU PERFIL</p><h1>{name}</h1><p>Temporada QuiniDerio 2026/27</p></div><div className="profileCard"><div className="bigAvatar">{name[0]}</div><div><b>{name}</b><small>Jugador QuiniDerio</small></div><strong>0 pts</strong></div><div className="menuCards"><button><span>◈</span><div><b>Mis predicciones</b><small>Consulta tus elecciones de temporada</small></div><em>›</em></button><button><span>★</span><div><b>Predicción extra</b><small>Dinio: {dinio||"—"}</small></div><em>›</em></button><button><span>?</span><div><b>Cómo se puntúa</b><small>Reglas y sistema de puntos</small></div><em>›</em></button></div></section>}